### ISSUE TITLE
Andorid 的 Docker？

### ISSUE THREAD

**Issue by liuzheng** [msdx/MetaCOS#1]
表示这东西到时候会不会成为Android的Docker，我就纯瞎想一下
周末好好研究一下:smile:

**Comment by msdx** [comment]
会不会就不知道。不过我开始写的时候才发现，手头没那些图片素材。

**Comment by liuzheng** [comment]
什么图片素材？

**Comment by msdx** [comment]
@liuzheng712 做为一个牛X哄哄的流式加载操作系统的超级操作系统，怎么也得有个像样点的图标，还有里面选系统的两张图片。

**Comment by liuzheng** [comment]
这个不急，logo我找妹子设计就行了，系统图片么容易，截屏什么都可以的，ps也行，有个妹子可以帮忙小搞搞
